trigger:
  branches:
    include:
    - 'master'
    - 'devops'
    - 'dev'
  paths:
    exclude:
    - '*.md'
    - '*.user'    
    - '.git'    

pool:  
  name: Default

variables:
  dotnetver: '9.x'
  buildcfg: 'Debug'    

steps:
- task: UseDotNet@2
  displayName: 'use dotnet 9'
  inputs:
    version: '$(dotnetver)'
    includePreviewVersions: true
    installationPath: '$(Agent.ToolsDirectory)/dotnet'

- script: dotnet --info
  displayName: 'dotnet info'
  
- script: dotnet restore --verbosity normal
  displayName: 'dotnet restore'

- script: dotnet build --configuration $(buildcfg) --verbosity normal --no-restore
  displayName: "dotnet build"

- script: dotnet test --no-restore --no-build
  displayName: 'dotnet test'