

///////////////////////////////////////////////////////////////////////////////
// Note: this file is generated by `centazio dev gen-settings` - DO NOT MODIFY
///////////////////////////////////////////////////////////////////////////////

namespace Centazio.Core.Settings;


public record AzSettings {

  
  public required string ListFunctionApps { get; init; }
  
  public required string ListFunctions { get; init; }
  
  public required string DeleteFunctionApp { get; init; }
  
  public required string StartFunctionApp { get; init; }
  
  public required string StopFunctionApp { get; init; }
  
  public required string RunAzuriteArgs { get; init; }
}

public record FuncSettings {

  
  public required string LocalSimulateFunction { get; init; }
  
  public required string ShowLogStream { get; init; }
}

public record DotNetSettings {

  
  public required string CleanProject { get; init; }
  
  public required string BuildProject { get; init; }
  
  public required string PublishProject { get; init; }
  
}

public record LambdaSettings {

  
  public required string ShowLogStream { get; init; }

}

public record ConsoleCommandsSettings {

  
  public required AzSettings Az { get; init; }
  
  public required FuncSettings Func { get; init; }
  
  public required DotNetSettings DotNet { get; init; }
  
  public required LambdaSettings Lambda { get; init; }

}

public record AzureDefaultValuesSettings {

  
  public required string FunctionAppNameTemplate { get; init; }
  
  public required string AppServicePlanNameTemplate { get; init; }
  
  public required string WebSiteNameTemplate { get; init; }
  
  public required string AppServiceSkuName { get; init; }
  
  public required string AppServiceSkuTier { get; init; }

}

public record DefaultsSettings {

  
  public required string GeneratedCodeFolder { get; init; }
  
  public required int FunctionMaxAllowedRunningMinutes { get; init; }
  
  public required string ReadFunctionPollExpression { get; init; }
  
  public required string PromoteFunctionPollExpression { get; init; }
  
  public required string WriteFunctionPollExpression { get; init; }
  
  public required string OtherFunctionPollExpression { get; init; }
  
  public required ConsoleCommandsSettings ConsoleCommands { get; init; }
  
  public required AzureDefaultValuesSettings AzureDefaultValues { get; init; }

}

public record SecretsLoaderSettings {

  
  public required string Provider { get; init; }
  
  public string? SecretsFolder { get; init; }
  
  public string? ProviderKey { get; init; }
  
  public string? ProviderSecret { get; init; }

}

public record StagedEntityRepositorySettings {

  
  public required string Provider { get; init; }
  
  public required string ConnectionString { get; init; }
  
  public required string SchemaName { get; init; }
  
  public required string TableName { get; init; }
  
  public required bool CreateSchema { get; init; }
  
  public required int Limit { get; init; }
}

public record CtlRepositorySettings {

  
  public required string Provider { get; init; }
  
  public required string ConnectionString { get; init; }
  
  public required string SchemaName { get; init; }
  
  public required string SystemStateTableName { get; init; }
  
  public required string ObjectStateTableName { get; init; }
  
  public required string CoreToSysMapTableName { get; init; }
  
  public required string EntityChangeTableName { get; init; }
  
  public required bool CreateSchema { get; init; }

}

public record CoreStorageSettings {

  
  public required string Provider { get; init; }
  
  public required string ConnectionString { get; init; }
  
  public required string SchemaName { get; init; }
  
  public required string CtlSchemaName { get; init; }
  
  public required bool CreateSchema { get; init; }

}

public record AzFunctionsSettings {

  
  public string? Assembly { get; init; }
  
  public string? Region { get; init; }
  
  public string? ResourceGroup { get; init; }
  
  public string? FunctionAppName { get; init; }
  
  public string? AppServicePlanName { get; init; }
  
  public string? WebSiteName { get; init; }
  
  public string? AppServiceSkuName { get; init; }
  
  public string? AppServiceSkuTier { get; init; }
}

public record AzureSettings {

  
  public required string Region { get; init; }
  
  public required string ResourceGroup { get; init; }
  
  public string? FunctionAppName { get; init; }
  
  public string? AppServicePlanName { get; init; }
  
  public string? WebSiteName { get; init; }
  
  public string? TenantId { get; init; }
  
  public string? KeyVaultName { get; init; }
  
  public string? KeySecretNameTemplate { get; init; }
  
  public required List<AzFunctionsSettings> AzFunctions { get; init; }
}

public record AwsSettings {

  
  public required string Region { get; init; }
  
  public string? AccountName { get; init; }
  
  /// <summary>
  /// This template string is used to get the Aws Store Id by replacing `&lt;environment&gt;` with the required environment
  /// </summary>
  public string? SecretsManagerStoreIdTemplate { get; init; }
  
  /// <summary>
  /// The amount of time (in seconds) that Lambda allows a function to run before stopping it. The maximum allowed value is 900 seconds.
  /// </summary>
  public required int MemorySize { get; init; }
  
  /// <summary>
  /// The amount of memory available to the function at runtime. Increasing the function memory also increases its CPU allocation. The default value is 128 MB. The value can be any multiple of 1 MB.
  /// </summary>
  public required int Timeout { get; init; }
}
