#!/bin/bash
CURR_DIR=$(pwd)
SLN_DIR="../centazio3"

dotnet tool uninstall --local Centazio.Cli
rm -rf ./config/
cd $SLN_DIR
./centazio dev publish -p
cd $CURR_DIR
dotnet new tool-manifest --force
dotnet tool install --prerelease --local --add-source ../centazio3/packages/ Centazio.Cli
dotnet centazio "$@"
